apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bojpawnprodingress
  annotations:
    #nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    name: bojpawnprodingress
  namespace: group-1-prod
spec:
  #Ref 
  #- https://kubernetes.github.io/ingress-nginx/examples/rewrite/
  #- https://kubernetes.github.io/ingress-nginx/user-guide/ingress-path-matching/
  ingressClassName: nginx
  rules:
  - host: tcc-01.th1.proen.cloud
    http:
      paths:
      - pathType: Prefix
        path: "/bojpawn(/|$)(.*)"
        backend:
          service:
            name: bojpawnfront-svc
            port: 
              number: 80
      - pathType: Prefix
        path: "/bojpawnback(/|$)(.*)"
        backend:
          service:
            name: bojpawnapi-svc
            port: 
              number: 80